### ISSUE TITLE
Using an unsupported aspect ratio in an image config tag prevents whenOdysseyLoaded from firing.

### ISSUE THREAD

**Issue by thomasbrettell** [abcnews/odyssey#10] opened 2023-08-14 07:27 UTC
```
#configsm3x2md3x3lg3x2xl3x2

[[Image: racist poster]](https://github.com/abcnews/odyssey/issues/new#)
```
The above tag and link was in Core and since an aspect ratio of 3x3 for the md size does not exist all whenOdysseyLoaded usages would never resolve.

**Comment by drzax** [comment] 2023-08-15 00:00
What behaviour would you expect when an unsupported aspect ratio is encountered? We could make it throw or simply ignore it? I know 3x3 is essentially the same as 1x1 which is a supported ratio, but I'd like to avoid parsing and calculating that kind of thing.

**Comment by drzax** [comment] 2023-10-17 04:45
I'm going to close this as won't fix for now since it's easy to correct in the content and it's unclear what the preferred behaviour would be.

**Closed as completed by drzax** 2023-10-17 04:45 UTC

**Comment by phocks** [comment] 2023-10-17 06:43
Hey @thomasbrettell was it immediately obvious that this was the cause of whenOdysseyLoaded not firing? I guess if not and it took ages to track down the problem, a better behaviour might be throw some kind of error in the promise, so we know exactly why it's happening and not just wait forever.
